<?php

/**
 * implement alter form hook
 */

function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
    if ($form_id == 'comment_comment_form') {
        // if (isset($form['type']) && $form['type']['#value'] . '_node_settings' == $form_id) {
        //   $upload_enabled_types = \Drupal::config('mymodule.settings')
        //     ->get('upload_enabled_types');
        //   $form['workflow']['upload_' . $form['type']['#value']] = array(
        //     '#type' => 'radios',
        //     '#title' => t('Attachments'),
        //     '#default_value' => in_array($form['type']['#value'], $upload_enabled_types) ? 1 : 0,
        //     '#options' => array(
        //       t('Disabled'),
        //       t('Enabled'),
        //     ),
        //   );

        //   // Add a custom submit handler to save the array of types back to the config file.
        $form['actions']['submit']['#submit'][] = 'after_sumbission';
        $form['actions']['submit']['#value'] = t('comment');

        // }
    }
}

function after_sumbission($form, &$form_state)
{
    dump($form_state);
    die();
}
